# Site Settings
development:
  url: http://localhost:4000
staging:
  url:
production:
  url: https://wallscleaningservices.com

# Site Language
locale:

# Theme Settings
theme: threshold

# Collection Defaults
defaults:
  - scope:
      type: posts
    values:
      layout: post
  - scope:
      type: pages
    values:
      layout: page
