# Site Settings
url:

# Jekyll Configuration
encoding: UTF-8
permalink: /:title/

# Markdown Processing
markdown: kramdown
kramdown:
  input: GFM

# Sass/SCSS Settings
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Collection Defaults
defaults:
- scope:
    type: pages
  values:
    layout: page

# Autoprefixer Plugin Settings - https://github.com/vwochnik/jekyll-autoprefixer
autoprefixer:
  browsers:
    - last 2 versions
  only_production: true

# File Handling
# include: [_pages]
exclude: [lib, config.rb, .sass-cache, Capfile, config, log, Rakefile, Rakefile.rb, tmp, Gemfile, Gemfile.lock, README.md, LICENSE.md, node_modules, package.json]

# CloudCannon Options
_options:
  layout:
    hidden: true

# CloudCannon Comment Defaults
_comments:
  title: Main headline of the page, also used in html title tag (required)
  seo_title: Will overwrite the html title tag (not required)
  description: Description text Google uses in search results
  emails: Form recipients
  email_subject: Form email subject
  featured_image: Image used when sharing on Facebook (default image will be used if blank)
  categories: Capitalize your categories (e.g. "Vacation Photos" "YouTube Video")
  tags: Capitalize your tags (e.g. "Vacation Photos" "YouTube Video")
  noindex: This tells Google (and other search engines) not to add this page to its index
  permalink: Website address for this page
  video_embed: Did you embed an video iframe?
